FROM python:3.10


COPY /requirements.txt / 

RUN pip install --upgrade pip & \
    pip install -r requirements.txt

WORKDIR /streamlit

COPY /src /streamlit/src
#COPY /.streamlit /streamlit/.streamlit
#COPY /main.py /streamlit

EXPOSE 7999

ENTRYPOINT ["streamlit", "run", "/streamlit/src/main.py", "--server.port=7999"]